### ISSUE TITLE
Getting it to run on MAC

### ISSUE THREAD

**Issue by GuidoDechamps** [tobiasflohre/movie-database#27]
This is not so much an issue as more of a story of how i got it to run on my mac with the latest docker. Hopefully it can help other people. Especially to slow Tomcat startup took me some time to fix.
## 1. Perform the actions mentioned in the Read.me

```
- modify the hosts file 
- install node.js, grunt, npm , bower  
```
## 2. Modify file path in build script.

I changed the file path it from /opt/ to /tmp/ 
As a result  i modified the build script to execute some task as root user due to the file path. 

**changed build script: build.sh**

```
echo "Build all services..."
mvn clean install
cd movie-database-shop-app
bower install
sudo grunt
sudo chmod 777 /tmp/moviedatabase
sudo rm -rf /tmp/moviedatabase/shop-app
sudo cp  -R dist/. /tmp/moviedatabase/shop-app
cd ..
```
## 3. Running it with latest docker.

The version of docker on my mac is:

```
Client:
Version:      1.10.2
API version:  1.22
Go version:   go1.5.3
Git commit:   c3959b1
Built:        Mon Feb 22 22:37:33 2016
OS/Arch:      darwin/amd64

Server:
Version:      1.10.2
API version:  1.22
Go version:   go1.5.3
Git commit:   c3959b1
Built:        Mon Feb 22 22:37:33 2016
OS/Arch:      linux/amd64

docker-compose version 1.6.0
```

Since the latest docker has changed a bit, also concerning networking i needed to modify the docker-compose file to the v2. I also added some dependencies between the modules.

```
version: '2'
services:
  redis:
  # Security Storage
    image: redis
  monitoring:
    build:
      context: ./movie-database-monitoring
    ports:
     - "8083:8083"
  movies:
    build:
      context: ./movie-database-movies
    ports:
     - "8080:8080"
    depends_on:
      - monitoring
  actors:
   build:
      context: ./movie-database-actors
    ports:
     - "8082:8082"
    depends_on:
      - monitoring
  navigation:
    build:
      context: ./movie-database-navigation
    ports:
     - "8081:8081"
    depends_on:
      - movies
      - actors
  shop:
    build:
      context: ./movie-database-shop-rest
    ports:
     - "8084:8084"
    depends_on:
      - navigation
  shopgui:
    build:
      context: ./movie-database-shop-app
    depends_on:
      - shop
    ports:
     - "80:80"
    #workaround to make sure that the http server starts at last
    volumes_from:
     - movies
     - actors
     - navigation
     - shop
```
## 4. Building it it with latest docker.

In order to get the all the services to run with docker i need to execute the following commands
- **./build.sh** (build jars, copy angular frontend to locations)
- **docker-compose build** (build all images, you can add this to the build script, so building requires just executing one script)
- **docker-compose up** (create containers and start them)
## 5. LibraryvVersion upgrade.

While i was add it i also upgraded to java 8 and changed to the latest spring-boot version as well the latest spring boot admin starter. I had to make one code change due to a api change. This is not relevant in order to get it to work. But it does work with new version of libraries and java 8 (also specify in docker files).

```
spring-boot-admin-.version:1.3.2
spring-boot-starter-parent.version:1.3.3.RELEASE
```
## 6. Startup.

Going to 
http://moviedatabase.com/movie-app/login shows the app login page
http://moviedatabase.com:8083/#/overview shows the spring admin page of all the spring boot services

However it can be that it takes a long time before the services start up. This can be due to the issue discussed next.
## 7. Slow tomcat startup (more then 5 minutes)

On my machine it took the services a very long time to boot. 5 minutes. After some googeling i found that this was due to a known issue with entrophy in tomcat.

In the logging i saw:

```
2016-03-14 08:48:23.391  INFO 5 --- [ost-startStop-1] o.s.c.n.zuul.ZuulFilterInitializer       : Starting filter initializer context listener
2016-03-14 08:56:51.815  INFO 5 --- [ost-startStop-1] o.a.c.util.SessionIdGeneratorBase        : Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took **[508,360]** milliseconds.
```

More info why that is can be found here: 
http://www.labouisse.com/misc/2014/06/19/tomcat-startup-time-surprises/
The solution was clearly documented on spring-boot-docker documentation: https://spring.io/guides/gs/spring-boot-docker/

So i simply needed to modify all the docker files to set the “java.security.egd” property

```
ENV JVM_OPTS=-Djava.security.egd=file:/dev/./urandom
ENTRYPOINT java $JVM_OPTS -jar /service.jar $ARGS
```

After a rebuild the services now boot quickly.
